import os
import subprocess

def generate_scad():
    # SCAD Code String
    # Updated for Custom PCB: 60x90mm
    # Ports: Top Left (Audio), Top Right (USB)
    # Buttons: Front Bottom Left (3x Row), Front Bottom Right (2x Col)
    
    scad = r"""
// Walkman Custom PCB Case
// Generated by Python

$fn = 60; 

// --- Dimensions ---
pcb_w = 60;
pcb_h = 90;
pcb_thick = 15; // Clearance for components

// Internal padding
pad = 3;

width = pcb_w + pad*2 + 4; // +Walls
height = pcb_h + pad*2 + 4;
depth = pcb_thick + 4; // +Walls
wall = 2.0;
corner_r = 3.0;

// --- Colors ---
c_clear = [0.9, 0.95, 0.98, 0.3]; 
c_pcb   = [0.2, 0.5, 0.2, 1];
c_btn   = [1.0, 0.4, 0.0, 1];     
c_port  = [0.7, 0.7, 0.7, 1];

module rounded_box(dim, r) {
    if (r == 0) cube(dim);
    else hull() {
        translate([r, r, 0]) cylinder(h=dim[2], r=r);
        translate([dim[0]-r, r, 0]) cylinder(h=dim[2], r=r);
        translate([dim[0]-r, dim[1]-r, 0]) cylinder(h=dim[2], r=r);
        translate([r, dim[1]-r, 0]) cylinder(h=dim[2], r=r);
    }
}

module shell() {
    color(c_clear) 
    difference() {
        rounded_box([width, height, depth], corner_r);
        
        // Hollow inside
        translate([wall, wall, wall])
            rounded_box([width-2*wall, height-2*wall, depth-2*wall], corner_r-1);
            
        // --- Cuts ---
        
        // Split for Lid (Optional, visualization only here)
        
        // 1. Audio Jack (Top Left)
        // Approx 15mm from left
        translate([15, height-10, depth/2])
            rotate([90, 0, 0])
            cylinder(h=20, r=4); 
            
        // 2. USB-C (Top Right)
        // Approx 15mm from right
        translate([width-15, height-10, depth/2])
            rotate([90, 0, 0])
            rounded_box([9, 4, 30], 1); // Slot shape centered? No, need to center properly
            
        translate([width-15 - 4.5, height-10, depth/2 - 2]) // Manual center adjustments
             cube([9, 20, 4]);

        // 3. Front Buttons Holes
        // Bottom Left: 3x Horizontal
        for(i=[0:2]) {
             translate([15 + i*12, 20, depth-5])
                cylinder(h=10, r=3.5);
        }
        
        // Bottom Right: 2x Vertical
        for(j=[0:1]) {
             translate([width - 15, 20 + j*12, depth-5])
                cylinder(h=10, r=3.5);
        }
    }
}

module pcb_mockup() {
    translate([wall + pad, wall + pad, wall]) {
        // PCB Board
        color(c_pcb)
        cube([pcb_w, pcb_h, 1.6]);
        
        // Audio Jack Module
        color([0.5,0,0.5])
        translate([5, pcb_h - 15, 1.6])
            cube([15, 15, 10]);
            
        // ESP32 Board (USB)
        color([0.1,0.1,0.1])
        translate([pcb_w - 25, 10, 1.6]) // Rotated or straight? Image shows USB Top Right
            cube([25, pcb_h-10, 5]); // Placeholder
            
        // USB Connector
        color(c_port)
        translate([pcb_w - 15, pcb_h - 2, 3])
            cube([8, 10, 3]);
    }
}

module buttons() {
    // Button Caps (Floating)
    
    // Bottom Left Cluster
    for(i=[0:2]) {
        translate([15 + i*12, 20, depth - 1])
        color(c_btn)
        cylinder(h=2, r=3);
    }
    
    // Bottom Right Cluster
    for(j=[0:1]) {
        translate([width - 15, 20 + j*12, depth - 1])
        color(c_btn)
        cylinder(h=2, r=3);
    }
}

module text_labels() {
    // SONY or custom text
    color([0.2, 0.2, 0.2])
    translate([width/2, height/2 + 10, depth - 0.5])
    linear_extrude(1)
    text("WALKMAN", size=6, font="Arial:style=Bold", halign="center");
    
    // Tape window style decoration
    color([0.1, 0.1, 0.1, 0.8])
    translate([10, height/2 - 10, depth - wall - 0.1])
        cube([width-20, 30, 0.2]);
}

// --- Main ---

union() {
    shell();
    buttons();
    pcb_mockup();
    text_labels();
}
    """
    return scad

def main():
    base_dir = os.path.dirname(os.path.abspath(__file__))
    output_scad = os.path.join(base_dir, "walkman_pcb_fit.scad")
    output_stl = os.path.join(base_dir, "walkman_pcb_fit.stl")
    
    print(f"Generating SCAD to {output_scad}...")
    
    with open(output_scad, "w") as f:
        f.write(generate_scad())
    
    # Force Homebrew-installed OpenSCAD path
    exe = "/opt/homebrew/bin/openscad"
    if not os.path.exists(exe):
         # Fallback simple check
         exe = "/Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD"
            
    if os.path.exists(exe):
        print(f"Found OpenSCAD at {exe}. Exporting STL...")
        try:
            subprocess.run([exe, "-o", output_stl, output_scad], check=True)
            print(f"STL exported to {output_stl}")
        except subprocess.CalledProcessError as e:
            print("Error during export:", e)
    else:
        print("OpenSCAD executable not found. Cannot export STL.")

if __name__ == "__main__":
    main()
